<a href="https://colab.research.google.com/github/YongHeeJang/Python/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr = np.array([1,2,3,4])

In [ ]:
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [ ]:
# 0으로 초기화된 배열
# 0으로 초기화 해야 하는 이유가 있다.
# 앱은 종료될 때 메모리를 반납하고 끝낸다. 
# 이 때,메모리는 완전히 비우지는 않고 사용할 수 있다고 남기고 종료된다.
# 정수가 아니라 항상 실수를 사용할 수 있도록 0이 아니라 0.으로 출력된다.
# 정수보다 실수가 더 속도가 느릴것 같지만, 모든 값이 실수로 통일되면 속도가 더 빨라진다.
# 속도를 위해 기본적으로 실수형을 사용한다.
arr = np.zeros((3,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
# 빈 값으로 만들어진 배열
# empty를 해주면, 완전히 0가 되는게 아니라 이상한 값들이 나옴
# 다른 프로그램이 사용했던 찌거기가 남아 있는 것이다.
# 때로는 0으로 다 바꿔주는 것이 더 좋을 수도 있다.
arr = np.empty((4,4))
print(arr)

[[2.23680039e-316 3.80430547e-322 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 1.50008929e+248 4.31174539e-096 9.80058441e+252]
 [1.23971686e+224 2.59031995e-144 6.06003395e+233 1.06400250e+248]
 [2.59050167e-144 5.22286946e-143 2.66023306e-312 0.00000000e+000]]


In [ ]:
# 1로 가득찬 배열을 만든다.
arr = np.ones((3,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# 배열의 생성
arr = np.arange(10)

print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# ndarray 배열의 모양, 차수, 데이터 타입 확인

arr = np.array([[1,2,3],
                [4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
arr.shape
# 모르는 array를 받았을 때는 습관적으로 shape과 dimension을 확인하는 것이 좋다.

(2, 3)

In [ ]:
arr.ndim

2

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
# data type 바꾸기
# 파이썬은 데이터를 입력할 때, 데이터 타입을 정하는 동적 언어이다.
arr_float = arr.astype(np.float64)
arr_float.dtype

dtype('float64')

In [ ]:
arr_str = np.array(['1','2','3'])
arr_str.dtype # dtype('<U1')이라는 것은 문자형 중에서도 유니코드 형태라는 것을 말한다.

dtype('<U1')

In [ ]:
arr_int = arr_str.astype(np.int64)
arr_int.dtype

dtype('int64')

In [ ]:
# ndarray 배열의 연산

arr1 = np.array([[1,2],
                 [3,4]])
arr2 = np.array([[5,6],
                 [7,8]])

In [ ]:
# ndarray의 합
# 같은 차원의 값들끼리 더해졌다.
arr1 + arr2

array([[ 6,  8],
       [10, 12]])

In [ ]:
np.add(arr1, arr2)

array([[ 6,  8],
       [10, 12]])

In [ ]:
# ndarray의 곱
# 같은 차원의 값들끼리 곱했다.
arr1 * arr2

array([[ 5, 12],
       [21, 32]])

In [ ]:
np.multiply(arr1, arr2)

array([[ 5, 12],
       [21, 32]])

In [ ]:
# ndarray 배열 슬라이싱 하기

arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

In [ ]:
print(arr.ndim)
print(arr.shape)
print(arr.dtype)

2
(3, 3)
int64


In [ ]:
# ndarray 배열 슬라이싱 하기

arr_1 = arr[:2,1:3]
print(arr_1)

[[2 3]
 [5 6]]


In [ ]:
arr[0,2]

3

In [ ]:
arr[[0,1,2],
    [2,0,1]]

array([3, 4, 8])

In [ ]:
idx = arr > 3
print(idx)

[[False False False]
 [ True  True  True]
 [ True  True  True]]


In [ ]:
# 전체 배열에서 특정 조건을 만족하는 것만 뽑아내기
# 예를들어, 3보다 큰 값만 뽑기
print(arr[idx])

[4 5 6 7 8 9]


In [ ]:
redwine = np.loadtxt(fname='winequality-red.csv',delimiter=';', skiprows=1) #구별자로 세미콜론을 이용했다고 정하는 것
# 첫줄은 데이터가 아니라 헤더이다. 첫줄을 건너 뛰기 위해서 skiprows를 지정
print(redwine)

[[ 7.4    0.7    0.    ...  0.56   9.4    5.   ]
 [ 7.8    0.88   0.    ...  0.68   9.8    5.   ]
 [ 7.8    0.76   0.04  ...  0.65   9.8    5.   ]
 ...
 [ 6.3    0.51   0.13  ...  0.75  11.     6.   ]
 [ 5.9    0.645  0.12  ...  0.71  10.2    5.   ]
 [ 6.     0.31   0.47  ...  0.66  11.     6.   ]]


In [ ]:
# 넘파이를 이용한 기초 통계 분석
# 합계(모든 항목)
print(redwine.sum())
# 평균
print(redwine.mean())
# 모든 항목에 대해서 합이나 평균을 구하는 것은 별 의미가 없다. 축을 따라 항목별로 합이나 평균을 구해주는 것이 좋다.


152084.78194
7.926036165311652


In [ ]:
# 축
# 축이라는 개념을 잘 알아야 한다.
# 가로 방향이 0번축, 세로 방향이 1번축이다.
# 0번축을 기준으로 sum을 하면, 0번 축을 기준으로 하기 때문에 column별로 합계를 구해준다.
print(redwine.sum(axis=0))
print(redwine.mean(axis=0))

[13303.1       843.985     433.29     4059.55      139.859   25384.
 74302.       1593.79794  5294.47     1052.38    16666.35     9012.     ]
[ 8.31963727  0.52782051  0.27097561  2.5388055   0.08746654 15.87492183
 46.46779237  0.99674668  3.3111132   0.65814884 10.42298311  5.63602251]


In [ ]:
# 첫번째 column 슬라이싱
column1 = redwine[:, 0]
print(column1)
print(column1.mean())

[7.4 7.8 7.8 ... 6.3 5.9 6. ]
8.31963727329581


In [ ]:
# column별로 최대값 가져오기
print(redwine.max(axis=0))
print(redwine.min(axis=0))


[ 15.9       1.58      1.       15.5       0.611    72.      289.
   1.00369   4.01      2.       14.9       8.     ]
[4.6     0.12    0.      0.9     0.012   1.      6.      0.99007 2.74
 0.33    8.4     3.     ]
